version: '3.8'

networks:
  pronas-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  minio_data:
  prometheus_data:
  grafana_data:

services:
  # ----------------- INFRASTRUCTURE -----------------
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - pronas-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ... (outros serviços de infra como redis, elasticsearch, minio - sem alterações) ...
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - pronas-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    
  # ----------------- BACKEND SERVICES -----------------
  auth-service:
    build:
      context: ./services/auth-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8000"
    networks:
      - pronas-network
    restart: unless-stopped

  ai-service:
    build:
      context: ./services/ai-service
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8002:8000"
    networks:
      - pronas-network
    restart: unless-stopped

  projects-service:
    build:
      context: ./services/projects-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - AI_SERVICE_URL=${AI_SERVICE_URL}
    # Comando para rodar migrações antes de iniciar o servidor
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      postgres:
        condition: service_healthy
      ai-service:
        condition: service_started
    ports:
      - "8003:8000"
    networks:
      - pronas-network
    restart: unless-stopped

  institutions-service:
    build:
      context: ./services/institutions-service
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8004:8000"
    networks:
      - pronas-network
    restart: unless-stopped

  # ----------------- FRONTEND SERVICE -----------------
  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3000:3000"
    networks:
      - pronas-network
    depends_on:
      - kong
    restart: unless-stopped

  # ... (outros serviços como kong, prometheus, grafana - sem alterações) ...
  kong:
    image: kong:3.4-alpine
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./infrastructure/kong:/kong/declarative
    ports:
      - "8080:8000"  # Proxy
      - "8443:8443"  # Proxy SSL
      - "8081:8001"  # Admin API
    networks:
      - pronas-network
    restart: unless-stopped