_format_version: "3.0"
_comment: "Declarative Kong configuration for PRONAS/PCD System"

services:
- name: auth-service
  url: http://auth-service:8000
  routes:
  - name: auth-routes
    paths:
    - /auth

- name: projects-service
  url: http://projects-service:8000
  routes:
  - name: projects-routes
    paths:
    - /projects

- name: institutions-service
  url: http://institutions-service:8000
  routes:
  - name: institutions-routes
    paths:
    - /institutions

- name: ai-service
  url: http://ai-service:8000
  routes:
  - name: ai-routes
    paths:
    - /ai

- name: catalog-service
  url: http://catalog-service:8000
  routes:
  - name: catalog-routes
    paths:
    - /catalog

- name: frontend-service
  url: http://frontend:3000
  routes:
  - name: frontend-routes
    paths:
    - /
