apiVersion: v1
kind: Namespace
metadata:
  name: pronas-pcd
  labels:
    name: pronas-pcd
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pronas-quota
  namespace: pronas-pcd
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Gi
    requests.storage: 500Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pronas-limits
  namespace: pronas-pcd
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container