"""create catalog items table

Revision ID: a1b2c3d4e5f6
Revises: 
Create Date: 2025-09-10 01:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('item_code', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('suggested_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_id'), 'catalog_items', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_items_item_code'), 'catalog_items', ['item_code'], unique=False)
    op.create_index(op.f('ix_catalog_items_name'), 'catalog_items', ['name'], unique=False)
    op.create_index(op.f('ix_catalog_items_source'), 'catalog_items', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_items_source'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_name'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_item_code'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###