apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-service
  namespace: pronas-pcd
  labels:
    app: projects-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projects-service
  template:
    metadata:
      labels:
        app: projects-service
    spec:
      containers:
      - name: projects-service
        image: ghcr.io/pronas-pcd/projects-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: AI_SERVICE_URL
          value: "http://ai-service:8000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: projects-service
  namespace: pronas-pcd
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: projects-service